/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Project' 
 * Target:  'McuSTUDIO_F470VET6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32f4xx.h"

/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.3.3 */
#define __PERF_COUNTER__ 1


#endif /* RTE_COMPONENTS_H */
